# pylint: disable-all
# flake8: noqa

"""Corrected the profile

Revision ID: 6841a259d244
Revises: 657b53bc89f6
Create Date: 2025-05-07 09:08:19.654427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6841a259d244"
down_revision: Union[str, None] = "657b53bc89f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("contacts", sa.JSON(), nullable=True))
    op.drop_column("profiles", "contact")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "contact",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("profiles", "contacts")
    # ### end Alembic commands ###
