"""Extend product
status enum

Revision ID: 6da641908bed
Revises: 42f08dd036dd
Create Date: 2025-06-02 11:11:10.949495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da641908bed'
down_revision: Union[str, None] = '42f08dd036dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.execute("ALTER TYPE productstatus ADD VALUE 'DEPRECATED' AFTER 'ARCHIVED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS productstatus_temporary CASCADE")
    op.execute("UPDATE products SET status = 'DRAFT' WHERE status = 'DEPRECATED'")
    op.execute("ALTER TYPE productstatus RENAME TO productstatus_temporary")
    op.execute("CREATE TYPE productstatus AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED')")
    op.execute("""
        ALTER TABLE products
        ALTER COLUMN status DROP DEFAULT,
        ALTER COLUMN status TYPE productstatus
        USING status::text::productstatus,
        ALTER COLUMN status
        SET DEFAULT 'DRAFT'::productstatus
    """)
    op.execute("DROP TYPE productstatus_temporary")
